id: P676366DB
initial_creation_type: input
source_metadata:
  title: Śrī Siṃha
  language: bo
  description: 'Texts by and about Śrī Siṃha (shrI sing+ha/shrI seng+ha), one of the
    early masters of the Dzogchen lineage:'
  volume:
    13253dbc4fda41e6ab5a729b1340da31:
      title: Unravelling Mantra’s Meaning in The Heart of Wisdom Sūtra
      parent: Commentaries
created_at: '2022-03-01T02:24:55.027246'
last_modified_at: '2022-03-01T02:24:55.027250'
